name: Test

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: install, build, and test
        run: |
          yarn install
          yarn build
          yarn test
        env:
          CI: true
      
      - name: Deploy coverage to codacy
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          # project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          api-token: ${{ secrets.CODACY_API_TOKEN }}
          coverage-reports: coverage/lcov.info
